-- Run this in the Supabase SQL Editor (Table Editor doesn't do bulk work
-- like this). Safe to re-run — the column add, policy, and insert are all
-- idempotent. (A live check against the actual database while building
-- this found the `slug` column and all 36 rows already present — looks
-- like this, or something equivalent, was already run by hand at some
-- point. This file is still worth keeping/running so the schema is
-- captured in the repo, and it'll no-op cleanly against existing data.)
--
-- What this does:
--   1. Adds a `slug` column to `businesses`, matching the filename/id each
--      listing already uses under src/content/listings/*.json — this is
--      the join key /l/[slug].astro uses at build time to find the
--      matching businesses row (for the "Claim This Listing" feature).
--   2. Adds a public read policy so an anonymous build-time query (and any
--      visitor, e.g. to check "is this claimed yet?") can see approved
--      businesses. There was no SELECT policy on this table before now —
--      only owners could read their own row.
--   3. Backfills one businesses row per existing listing (owner_id left
--      NULL — unclaimed — approved = true, since these are the site's
--      real, already-published listings). Without this, none of the 36
--      real listings on the site would have anything for "Claim This
--      Listing" to attach to.

alter table public.businesses
  add column if not exists slug text unique;

-- drop-then-create rather than a bare CREATE POLICY: Postgres has no
-- CREATE POLICY IF NOT EXISTS, and this needs to be safe to re-run.
drop policy if exists "Public can view approved businesses" on public.businesses;

create policy "Public can view approved businesses"
  on public.businesses
  for select
  to anon, authenticated
  using (approved = true);

insert into public.businesses
  (slug, name, category, neighborhood, phone, website, description, hours, years_in_business, licensed_insured, address, approved)
values
  ('rclcanada-edmonton', 'RCLcanada', 'landscaping-lawn-care', '', '(780) 910-3046', 'https://rclcanada.com/', 'A long-standing, family-run landscape contractor in Edmonton offering design-build services such as sod, stonework, decks, fencing, irrigation and outdoor lighting, along with a retail landscape supply yard.', '', 45, false, '9535 62 Ave, Edmonton, AB', true),
  ('weed-patrol-edmonton', 'Weed Patrol', 'landscaping-lawn-care', '', '(780) 413-9333', 'https://www.weedpatrol.ca/', 'An Edmonton lawn care company focused on weed control, liquid fertilization, core aeration and overseeding, serving residential customers across the city with pet-friendly treatment programs.', '', 37, false, '7235 Girard Road NW, Edmonton, AB T6B 2C5', true),
  ('hellamaid-edmonton', 'Hellamaid', 'house-cleaning', '', '587-287-6243', 'https://hellamaid.ca/house-cleaning-services-edmonton/', 'An online-bookable house cleaning service covering Edmonton, St. Albert, and Sherwood Park, offering standard, deep, move-out, and eco-friendly cleaning with recurring plans for homes and short-term rentals.', '', null, false, '12420 104 Ave NW, Edmonton, AB', true),
  ('jetco-plumbing-heating-edmonton', 'Jetco Plumbing & Heating', 'plumbers', '', '(780) 451-2732', 'https://jetcomechanical.com/', 'A long-running, locally owned Edmonton plumbing and mechanical contractor handling everything from hot water tanks and tankless heaters to gas lines, furnace repair, and 24/7 emergency service for homes and businesses.', '', 70, false, '15035 114 Ave NW, Edmonton, AB', true),
  ('fair-and-square-roofing-edmonton', 'Fair and Square Roofing Inc', 'roofing-roof-repair', '', '780-499-9668', 'https://fairandsquareroofing.com/', 'A full-service roofing contractor based in Edmonton offering residential and commercial roof replacement, repairs, and eavestrough work, along with extras like drone inspections and winter snow removal. Also serves St. Albert and Sherwood Park with a strong track record of positive customer reviews.', '', null, false, '5715 185 St NW, Edmonton, AB', true),
  ('pro-co-painting-edmonton', 'Pro Co Painting', 'painters-painting-contractors', '', '(780) 707-2521', 'https://www.procopainting.ca/', 'A locally based Edmonton painting contractor with over a decade of experience handling residential and commercial interior and exterior painting projects.', '', 12, false, '4607 92 Ave NW, Edmonton, AB', true),
  ('ipaint-painting-edmonton', 'iPaint Painting', 'painters-painting-contractors', '', '780-938-9555', 'https://ipaintpainting.ca/', 'An in-house painting crew serving Edmonton and nearby communities with interior, exterior, and cabinet painting, backed by MPI certification and a multi-year workmanship warranty.', '', null, true, '9821 33 Ave NW, Edmonton, AB', true),
  ('excel-heating-air-conditioning-edmonton', 'Excel Heating & Air Conditioning', 'furnace-heating-repair', '', '780-905-9594', 'https://excelhomecomfort.com/', 'A Carrier Factory Authorized Dealer serving the Edmonton area since 2007, offering furnace repair, installation, and maintenance from NATE-certified technicians for homes throughout the region.', '', 19, true, '16551 75 Street NW, Edmonton, AB', true),
  ('sierra-electrical-edmonton', 'Sierra Electrical Ltd.', 'electricians', '', '780-944-9400', 'https://sierraelectrical.com/', 'A longstanding Edmonton electrical contractor handling residential and commercial work, from panel upgrades and rewiring to lighting installs and aluminum wiring corrections. Licensed and insured electricians have served the area for over three decades.', '', 35, false, '9808 45th Ave NW, Edmonton, AB', true),
  ('alberta-arborists-edmonton', 'Alberta Arborists', 'tree-removal-arborist', '', '780-448-0584', 'https://www.albertaarborists.com/', 'A long-running Edmonton tree care company offering hazardous and large tree removal, pruning, stump grinding, and emergency storm cleanup. Their ISA-certified crews are licensed, insured, and WCB-covered, drawing on more than 25 years of local experience.', '', 25, true, '#231, 6005 Gateway Blvd, Edmonton, AB', true),
  ('dust-queen-edmonton', 'Dust Queen', 'house-cleaning', '', '780-448-4973', 'https://dustqueen.com/', 'An Edmonton house cleaning company operating since 1989, offering recurring, one-time, and move-in/move-out residential cleaning as well as commercial cleaning through its Knight Clean division.', '', 37, false, '2907 Ellwood Dr SW, Edmonton, AB T6X 0B1', true),
  ('mode-built-edmonton', 'Mode Built', 'basement-development', '', '780-221-3433', 'https://modebuilt.ca/', 'An Edmonton renovation contractor operating for over a decade out of a northwest Edmonton design studio, handling basement development and legal basement suites alongside kitchen, bathroom, and full home remodeling.', '', 14, false, '18304 105 Ave NW #207, Edmonton, AB T5S 0C6', true),
  ('strata-electrical-edmonton', 'Strata Electrical', 'electricians', '', '780-893-3902', 'https://strataelectrical.com/', 'An Edmonton electrical contractor serving residential, commercial, restoration, and property-management clients, staffed by Master Electricians, Journeymen, and Apprentices handling everything from outlet installs and garage wiring to commercial electrical contracting.', '', null, false, '#1, 11830 152 St, Edmonton, AB T5V 1E3', true),
  ('modern-air-water-edmonton', 'Modern Air & Water', 'furnace-heating-repair', '', '780-475-6484', 'https://modernairwater.com/furnace-repair/', 'An Edmonton HVAC and plumbing company operating since 1976, providing furnace repair, installation, and maintenance along with air conditioning, hot water tank, duct cleaning, and indoor air quality services.', '', 50, false, '#4, 16327 130 Ave NW, Edmonton, AB T5V 1K5', true),
  ('save-on-roofing-edmonton', 'Save On Roofing', 'roofing-roof-repair', '', '780-257-6526', 'https://www.saveonroofing.ca/', 'An Edmonton roofing contractor with over 30 years of combined experience, offering roof replacement, repair, and leak inspection along with soffit, fascia, eavestrough, and siding installation.', '', 30, true, '45-5250 Chappelle Rd SW, Edmonton, AB T6W 5A5', true),
  ('mow-town-edmonton', 'Mow Town Edmonton', 'snow-removal', '', '587-254-3773', 'https://mowtownedmonton.com/', 'A Consumer Choice Award-winning Edmonton company providing residential and commercial snow removal, including plowing, sidewalk clearing, and de-icing for multi-family, retail, and industrial properties, alongside seasonal lawn care.', '', 10, false, '12829 52 St NW, Edmonton, AB T5A 3P8', true),
  ('home-services-edmonton-ltd-edmonton', 'Home Services Edmonton Ltd.', 'handyman-services', '', '780-239-1355', 'https://www.homeservicesedmonton.com/', 'An Edmonton handyman company run by owner Franz, handling general home repairs and maintenance, drywall and taping, interior painting and carpentry, and small renovation and flooring jobs.', '', null, false, 'Orchards Blvd SW, Edmonton, AB T6X 2B7', true),
  ('action-furnace-edmonton', 'Action Furnace', 'furnace-heating-repair', '', '780-970-2777', 'https://actionfurnace.ca/locations/edmonton/', 'An Edmonton heating and cooling company operating since 1975, offering furnace installation, repair, and tune-ups, heat pump and AC service, duct cleaning, and water heater installation and repair, with 24/7 service availability.', '', 50, false, '8441 Coronet Road, Edmonton, AB T6E 4N7', true),
  ('edmonton-painting-edmonton', 'Edmonton Painting', 'painters-painting-contractors', '', '587-400-7009', 'https://www.edmonton-painting.com/', 'An Edmonton painting company with 14 years of experience offering interior, exterior, commercial, and condominium painting services, with over 1,900 houses painted to date.', '', 14, false, '6444 157 Ave NW, Edmonton, AB T5Y 2N5', true),
  ('apollo-plumbing-edmonton', 'Apollo Plumbing', 'plumbers', '', '780-200-6870', 'https://apolloplumbing.ca/', 'An Edmonton-area residential and commercial plumbing and heating company serving the region since 1969, offering 24/7 emergency plumbing, drain cleaning, water heater repair and replacement, furnace repair, and sump pump service.', '', 57, true, '14507 130 Ave NW, Edmonton, AB T5L 3M5', true),
  ('artman-contracting-edmonton', 'Artman Contracting Ltd.', 'general-contractors', '', '780-462-5808', 'https://www.artman-contracting.com/', 'An Edmonton general contracting company handling residential and commercial renovations, including basement development, kitchen and bathroom renovations, full home remodeling, and commercial maintenance work.', '', null, true, '3911 Chrustawka Pl SW, Edmonton, AB T6W 5K6', true),
  ('general-landscape-edmonton', 'General Landscape', 'landscaping-lawn-care', '', '587-588-6641', 'https://generallandscape.ca/', 'An Edmonton landscaping and property maintenance company offering lawn maintenance, spring and fall cleanups, tree and shrub services, grading and drainage repair, sod and landscape lighting, and fence and deck construction.', '', null, false, '10654 82 Ave NW, Unit 334, Edmonton, AB T6E 2A7', true),
  ('gorilla-property-services-edmonton', 'Gorilla Property Services', 'snow-removal', '', '780-851-7213', 'https://gorillapropertyservices.com/franchisees/edmonton-property-services/', 'A locally owned and operated Edmonton property maintenance franchise offering commercial and residential snow removal and salting alongside pressure washing, gutter and window cleaning, and year-round exterior maintenance.', '', null, true, 'Suite 20, 14811 114 Ave, Edmonton, AB T5M 4E5', true),
  ('prozone-ltd-edmonton', 'ProZone Ltd.', 'snow-removal', '', '780-452-9777', 'https://prozoneltd.ca/', 'A locally owned Edmonton contractor since 2009 providing commercial snow removal and sanding alongside asphalt, concrete, and landscaping supply services for commercial and municipal clients.', '', 17, true, '13919 Mark Messier Trail NW, Edmonton, AB T6V 0H8', true),
  ('rg-handyman-edmonton', 'RG Handyman', 'handyman-services', '', '587-853-5409', 'https://www.rghandyman.ca/', 'An owner-operated handyman business tackling the small jobs many contractors skip in west and southwest Edmonton, including drywall repair, door adjustments, fixture installation, and interior painting.', '', null, false, '', true),
  ('foy-tree-care-edmonton', 'Foy Tree Care', 'tree-removal-arborist', '', '780-885-4633', 'https://foytreecare.com/', 'A locally owned Edmonton tree service led by an ISA-certified arborist, handling tree removal, pruning, stump grinding, and tree health assessments. Carries WCB coverage and $2M liability insurance, with active client reviews across Google and social media.', '', null, true, '5328 Calgary Trail NW, Suite 1548, Edmonton, AB', true),
  ('tree-ninja-edmonton', 'Tree Ninja', 'tree-removal-arborist', '', '780-394-4024', 'https://treeninjaedmonton.com/', 'An Edmonton-based arborist company, operating since 2015, providing tree removal, pruning, cabling, and stump grinding for residential and commercial properties. Backed by ISA-certified arborists and a strong local reputation with hundreds of positive Google reviews.', '', 11, true, '11704 37B Ave NW, Edmonton, AB T6J 0K4', true),
  ('handyman-reality-edmonton', 'Handyman Reality', 'handyman-services', '', '780-707-5558', 'https://www.handymanreality.com/', 'An owner-operated Edmonton handyman business run by Don Moody since 2008, handling plumbing, electrical fixtures, drywall repair and painting, and general household repairs on a time-and-materials basis.', '', 18, false, '5328 Calgary Trail NW #1554, Edmonton, AB', true),
  ('alta-home-basement-development-edmonton', 'Alta Home Garages & More', 'basement-development', '', '403-827-7211', 'https://altahome.ca/edmonton-basement-developers/', 'A licensed Edmonton contractor that turns unfinished basements into livable space, handling design, permits, and full-scope construction for additions like bedrooms, home theatres, gyms, and legal suites. Backed by multiple HomeStars and TrustedPros awards and a physical office in Edmonton.', '', null, false, '8911 154 St NW, Edmonton, AB', true),
  ('diamond-contracting-edmonton', 'Diamond Contracting', 'general-contractors', '', '780-433-3166', 'https://www.diamondcontractingab.ca/', 'A family-owned Edmonton design-build renovation company that has served the city since 1999, taking on custom home builds, kitchen and bathroom remodels, basement developments, and home additions.', '', 27, false, '9754 27 Ave NW, Edmonton, AB', true),
  ('alair-homes-edmonton', 'Alair Homes Edmonton', 'basement-development', '', '780-809-4501', 'https://www.alairhomes.ca/edmonton/', 'The Edmonton branch of the Alair Homes design-build franchise, handling custom home builds and whole-home renovations including basement developments, additions, and major remodels.', '', null, false, '178 St NW, Edmonton, AB', true),
  ('ackard-contractors-edmonton', 'Ackard Contractors Ltd.', 'general-contractors', '', '780-414-0686', 'https://www.ackard.com/', 'A long-running Edmonton general contractor with roughly 40 years in business, handling kitchen and bathroom remodeling, structural repairs, electrical upgrades, and other home renovation projects.', '', 40, false, '10879 184 St NW, Edmonton, AB', true),
  ('always-plumbing-heating-edmonton', 'Always Plumbing & Heating', 'plumbers', '', '587-742-1359', 'https://alwaysplumbing.ca/', 'An Edmonton plumbing, heating, and cooling company serving the area since 1998, providing residential plumbing repairs, furnace service, and air conditioning work.', '', 28, false, '17633 114 Ave NW, Edmonton, AB', true),
  ('mcdonald-electrical-services-edmonton', 'McDonald Electrical Services', 'electricians', '', '780-292-1531', 'https://mcdonaldelectricalservices.ca/', 'An Edmonton residential electrical company run by a Certified Master Electrician, offering panel upgrades, LED lighting, EV charger installation, and basement, garage, and renovation wiring, with a 5-year warranty on work. States on its website that it is fully licensed and insured.', '', 7, true, '10212 74 St NW, Edmonton, AB T6E 3Z7', true),
  ('duty-cleaners-edmonton', 'Duty Cleaners', 'house-cleaning', '', '(780) 913-6565', 'https://dutycleaners.ca/', 'An Edmonton-based residential and commercial cleaning company with over eight years of local experience, providing regular house cleaning, deep cleans, move-in/move-out service, and add-ons like oven and window cleaning with online instant booking.', '', 8, false, '18615 71 Ave NW, Edmonton, AB', true),
  ('a-clark-roofing-siding-edmonton', 'A. Clark Roofing & Siding', 'roofing-roof-repair', '', '780-465-7571', 'https://www.aclark.ca/', 'An Edmonton roofing and siding contractor operating since 1953, handling roof repair, installation, inspections, and maintenance across residential and commercial properties, plus siding, eavestroughs, and insurance claims work.', '', 73, false, '3120 93 St NW, Edmonton, AB T6N 1C7', true)
on conflict (slug) do nothing;
