import type { APIRoute } from 'astro';
import { createSupabaseServerClient } from '../../lib/supabase-server';

// This route has to run per-request on the server, not be baked into a
// static HTML file at build time — it reads a one-time `code` value out of
// the URL and exchanges it for a session, which only makes sense live.
// Without this line, `astro build` would prerender it like every other
// page, and it would never see that `code`. The Netlify adapter set up in
// astro.config.mjs is what makes this opt-out possible at all.
export const prerender = false;

/**
 * Where the magic-link email points. The link itself is generated by
 * Supabase, but its target is the `emailRedirectTo` URL login.astro passed
 * to signInWithOtp() — which is this route.
 *
 * Supabase appends a one-time `?code=...` to that URL. Exchanging it here,
 * server-side, is what actually logs the visitor in: it turns that code
 * into a real session and writes it to cookies via the `setAll` in
 * supabase-server.ts, so the very next request (the redirect below) already
 * carries a valid session.
 */
export const GET: APIRoute = async ({ request, cookies, redirect, url }) => {
  const base = import.meta.env.BASE_URL;
  const join = (p: string) => `${base}${p}`.replace(/\/+/g, '/');

  const code = url.searchParams.get('code');
  if (!code) {
    return redirect(join('login?error=missing_code'));
  }

  const supabase = createSupabaseServerClient({ request, cookies });
  const { error } = await supabase.auth.exchangeCodeForSession(code);

  if (error) {
    return redirect(join(`login?error=${encodeURIComponent(error.message)}`));
  }

  // /dashboard doesn't exist yet (that's a later step) — this will 404
  // until it does. That's expected for now; the middleware below is what
  // will eventually gate it.
  return redirect(join('dashboard'));
};
